/* tslint:disable */
/* eslint-disable */
export const rton_worker_runtime_info: () => [number, number, number];
export const rton_worker_mode_switch: (a: any) => [number, number, number];
export const rton_worker_parse: (a: any) => [number, number, number];
export const rton_worker_rton_size: (a: any) => [number, number, number];
export const rton_worker_text_surface: (a: any) => [number, number, number];
export const rton_worker_open_text: (a: any) => [number, number, number];
export const rton_worker_tree: (a: any) => [number, number, number];
export const rton_worker_value_search: (a: any) => [number, number, number];
export const rton_worker_locate_text: (a: any) => [number, number, number];
export const rton_worker_text_search: (a: any) => [number, number, number];
export const rton_worker_hex_search: (a: any) => [number, number, number];
export const rton_worker_release_document: (a: any) => [number, number, number];
export const rton_worker_batch: (a: any) => [number, number, number];
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const wbg_rayon_poolbuilder_mainJS: (a: number) => any;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_start_worker: (a: number) => void;
export const initThreadPool: (a: number) => any;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
