[package]
name = "rton-editor-app"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true
authors = ["LambdaEd1th"]
description = "Editor for RTON resources"

[package.metadata.bundle]
name = "RTON Editor"
identifier = "io.github.lambdaed1th.rton_editor"
category = "public.app-category.developer-tools"
short_description = "Editor for RTON resources"
long_description = """
A cross-platform editor for converting, inspecting, and editing RTON resources.
"""

[package.metadata.bundle.bin.rton-editor]
name = "RTON Editor"
identifier = "io.github.lambdaed1th.rton_editor"
category = "public.app-category.developer-tools"
short_description = "Editor for RTON resources"
long_description = """
A cross-platform editor for converting, inspecting, and editing RTON resources.
"""

[[bin]]
name = "rton-editor"
path = "src/main.rs"

[dependencies]
dioxus-html = "0.7"
dioxus-free-icons = { version = "0.10", features = ["lucide"] }
fluent-bundle = "0.16"
rton_editor_core = { path = "../crates/core" }
serde_json = "1"
unic-langid = "0.9"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dioxus = { version = "0.7", features = ["desktop"] }
futures-timer = "3"
memmap2 = "0.9"
rfd = "0.17"

[target.'cfg(target_arch = "wasm32")'.dependencies]
dioxus = { version = "0.7", features = ["web"] }
js-sys = "0.3"
serde-wasm-bindgen = "0.6"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = [
    "Blob",
    "ClipboardEvent",
    "DataTransfer",
    "DataTransferItem",
    "DataTransferItemList",
    "Document",
    "DragEvent",
    "Element",
    "ErrorEvent",
    "File",
    "FileSystemDirectoryEntry",
    "FileSystemDirectoryReader",
    "FileSystemEntry",
    "FileSystemFileEntry",
    "HtmlAnchorElement",
    "MessageEvent",
    "Navigator",
    "Response",
    "Storage",
    "Url",
    "Window",
    "Worker",
    "WorkerOptions",
    "WorkerType",
] }
