[package]
name = "rton_editor_core"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_bytes = "0.11"
serde_json = "1.0"
serde_rton = { git = "https://github.com/LambdaEd1th/serde_rton.git", tag = "v0.3.2" }
serde_yaml = "0.9.33"
thiserror = "2.0"
toml = "1.1"
